version: '3.9'

services:
  app:
    build:
      context: ./API
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - s3
      - media

  media:
    build:
      context: ./media
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - s3

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  s3:
    image: minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
  minio_data:

